models/Employees.php
<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;

class Employees extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'employees';
    }

    /**
     * {@inheritdoc}
     */
    public $full_name;
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'company_id'], 'required'],
            [['id'], 'integer'],
            [['full_name'], 'safe'],
            [['phone'], 'string', 'max' => 15],
            [['email', 'first_name', 'last_name'], 'string', 'max' => 255],
            [['email'], 'email'],
            [['phone', 'email'], 'unique'],
            [['phone'], 'match' ,'pattern'=>'/^[0-9]+$/u', 'message'=> 'Contact No can Contain only numeric characters.'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'company_id' => 'Company',
            'email' => 'Email',
            'phone' => 'Phone'
        ];
    }

    public function getCompanies() {
        return $this->hasOne(Companies::className(), ['id' => 'company_id']);
    }

    public function search($params)
    {
        $this->load($params);
        
        $query = Employees::find()
                 ->select(['*', 'CONCAT(first_name, " ", last_name) full_name']);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> ['defaultOrder' => ['id' => SORT_DESC]],
            'pagination' => [
                'pageSize' => 2,
            ],
        ]);

        $dataProvider->sort->attributes['full_name'] = [
            'asc' => ['first_name' => SORT_ASC, 'last_name' => SORT_ASC],
            'desc' => ['first_name' => SORT_DESC, 'last_name' => SORT_DESC],
        ];

        $query->andFilterWhere([
            'company_id' => $this->company_id,
        ]);

        $query->andFilterWhere(['like', 'CONCAT(first_name, " ", last_name)', $this->full_name])
              ->andFilterWhere(['like', 'email', $this->email])
              ->andFilterWhere(['like', 'phone', $this->phone]);

        return $dataProvider;
    }
}

controllers/EmployeesController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use app\models\Employees;
use app\models\Companies;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

class EmployeesController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['get'],
                    'create' => ['get'],
                    'store' => ['post'],
                    'view' => ['get'],
                    'update' => ['get'],
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $arrUserPermission = ['admin@admin.com'];
        if(!Yii::$app->user->isGuest && !in_array(Yii::$app->user->identity->email, $arrUserPermission)) {
            throw new \yii\web\HttpException(403, "You're not allowed for this action.");
        }

        return parent::beforeAction($action);
    }

    public function actionIndex() {
        $searchModel = new Employees();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $filterCompanies = Companies::find()->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'filterCompanies' => ArrayHelper::map($filterCompanies, 'id', 'name')
        ]);
    }

    public function actionCreate() {
        $model = new Employees();
        $filterCompanies = Companies::find()->all();

        return $this->render('create', [
            'model' => $model,
            'filterCompanies' => ArrayHelper::map($filterCompanies, 'id', 'name')
        ]);
    }

    public function actionStore() {
        $model = new Employees();

        if ($model->load(Yii::$app->request->post())) {
            if(isset(Yii::$app->request->post('Employees')['id'])) {
                // update data Employees
                $model = Employees::find()->where(['id' => Yii::$app->request->post('Employees')['id']])->one();

                $model->first_name = Yii::$app->request->post('Employees')['first_name'];
                $model->last_name = Yii::$app->request->post('Employees')['last_name'];
                $model->company_id = Yii::$app->request->post('Employees')['company_id'];
                $model->email = (Yii::$app->request->post('Employees')['email'] == "") ? NULL : Yii::$app->request->post('Employees')['email'];
                $model->phone = (Yii::$app->request->post('Employees')['phone'] == "") ? NULL : Yii::$app->request->post('Employees')['phone'];
            } else {
                // TO CREATE EMPLOYEES
                $model->email = ($model->email == "") ? NULL : $model->email;
                $model->phone = ($model->phone == "") ? NULL : $model->phone;
            }

            if($model->save()) {
                Yii::$app->session->setFlash('success', 'Employee created successfully');
                return $this->redirect('index');
            } else {
                $filterCompanies = Companies::find()->all();
                Yii::$app->session->setFlash('error', 'There is something wrong, please try again');
                $action = (!isset(Yii::$app->request->post('Employees')['id'])) ? 'create' : 'update';
                return $this->render($action, ['model' => $model, 'filterCompanies' => ArrayHelper::map($filterCompanies, 'id', 'name')]);
            }
        } else {
            Yii::$app->session->setFlash('error', 'There is something wrong, please try again');
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function actionView($id){
        $model = Employees::find()->select(['*', 'CONCAT(first_name, " ", last_name) full_name'])->where(['id' => $id])->one();

        if($model == null || empty($model)) {
            throw new NotFoundHttpException('Employee does not exist.');
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = Employees::find()->where(['id' => $id])->select(['*', 'CONCAT(first_name, " ", last_name) full_name'])->one();
        $filterCompanies = Companies::find()->all();

        return $this->render('update', [
            'model' => $model,
            'filterCompanies' => ArrayHelper::map($filterCompanies, 'id', 'name')
        ]);
    }

    public function actionDelete($id) {
        $delete = Employees::find()->where(['id' => $id])->one()->delete();
        if($delete) {
            Yii::$app->session->setFlash('success', 'Employee deleted successfully');
        } else {
            Yii::$app->session->setFlash('error', 'There is something wrong, please try again');
        }

        return $this->redirect(['index']);
    }
}

views/employees/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\BomanagerMasterSupplier */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Create Employee';
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<script type="text/javascript">
    window.onload = function() {
        $( "#submit_form" ).submit(function( event ) {
            if($('#employees-first_name').val() != "" && $('#employees-last_name').val() != "" && $('#employees-company_id option:selected').val() != "") {
                $('.btn-save').html("<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Processing...");
                $('.btn-save').prop('disabled', true);
            }
        });
    }

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 43) {
            return false;
        }
        return true;
    }
</script>

<div>
	<h1><?= Html::encode($this->title) ?></h1>
	
    <?php $form = ActiveForm::begin(['id' => 'submit_form', 'action' => ['employees/store']]); ?>

    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?=
        $form->field($model, 'company_id')->widget(Select2::classname(), [
            'data' => $filterCompanies,
            'options' => ['placeholder' => 'Select a Company...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ])->label('Company');
    ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true])->input('email') ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true, "onkeypress" => "return isNumber(event)"]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-save']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employees/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\bootstrap\Modal;
use yii\bootstrap\ActiveForm;

$this->title = 'Employees';
$this->params['breadcrumbs'][] = $this->title;

$value_companies_id = "";
if(isset($_GET['Employees']['company_id'])){
    $value_companies_id = $_GET['Employees']['company_id'];
}
?>

<script type="text/javascript">
    window.onload = function() {
        $( "#delete_form" ).submit(function( event ) {
            $('.btn-delete').html("<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Processing...");
            $('.btn-delete').prop('disabled', true);
            $('.btn-cancel-delete').prop('disabled', true);
        });
    }
    function showModalDelete(id, full_name) {
        $("#modal").modal('show');
        $('#delete_form').attr('action', $('#delete_form').attr('action') + "?id="+id);
        $('.label-desc').html('Employee that are deleted cannot be returned. Are you sure you want to delete '+full_name+'?');
    }
</script>

<div>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php 
            echo Html::a('Create Employees', ['create'], ['class' => 'btn btn-success']);
        ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'full_name',
            [
                'attribute' => 'company_id',
                'value' => 'companies.name',
                'filter' => Select2::widget([
                    'name' => 'Employees[company_id]',
                    'data' => $filterCompanies,
                    'value' => $value_companies_id,
                    'options' => ['placeholder' => 'Select a company ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ])
            ],
            [
                'attribute' => 'email',
                'format' => 'email',
                'value' => function($model) {
                    return (is_null($model->email)) ? "" : $model->email;
                }
            ],
            [
                'attribute' => 'phone',
                'format' => 'html',
                'value' => function($model) {
                    return (is_null($model->phone)) ? "" : Html::a($model->phone, 'tel:'.$model->phone);
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'buttons'=>[
                    'view'=>function ($url, $model) {
                        return  Html::a('<span class="glyphicon glyphicon-eye-open"></span>', 
                                        Url::to(['employees/view', 'id' => $model->id]), 
                                        ['class' => 'btn btn-primary btn-xs']
                                );
                    },
                    'update'=>function ($url, $model) {
                        return  Html::a('<span class="glyphicon glyphicon-pencil"></span>', 
                                        Url::to(['employees/update', 'id' => $model->id]), 
                                        ['class' => 'btn btn-warning btn-xs']
                                );
                    },
                    'delete'=>function ($url, $model) {
                        return  Html::button('<span class="glyphicon glyphicon-trash"></span>', 
                                            [
                                                'onclick'=> 'showModalDelete("'.$model->id.'", "'.$model->full_name.'");',
                                                'data-toggle'=>'tooltip',
                                                'title'=>Yii::t('app', 'Delete'),
                                                'class' => 'btn btn-danger btn-xs'
                                            ]
                                );
                    },
                ],
            ]
        ],
    ]); ?>


</div>

<?php
Modal::begin([
    'header' => '<h3 style="color:red;">WARNING!</h3>',
    'id' => 'modal',
    'size' => 'modal-md',
]);

ActiveForm::begin(['action' => ['employees/delete'], 'id' => 'delete_form', 'method' => 'post', 'layout' => 'horizontal', ]); ?>
<?= Html::csrfMetaTags() ?>
<div class='modal-body'>
    <p class="label-desc" style="font-weight: normal;"></p>
</div>
<div class="modal-footer footer-delete">
    <div class='form-group'>
        <button class='btn btn-danger btn-delete'><span class='glyphicon glyphicon-trash'></span> Yes</button>
        <button type="button" class="btn btn-success btn-cancel-delete" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span> No</button>
    </div>
</div>
<?php
ActiveForm::end();
Modal::end();
?>

views/employees/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\select2\Select2;

$this->title = 'Update: '.$model->full_name;
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<script type="text/javascript">
    window.onload = function() {
        $( "#submit_form" ).submit(function( event ) {
            if($('#employees-first_name').val() != "" && $('#employees-last_name').val() != "" && $('#employees-company_id option:selected').val() != "") {
                $('.btn-save').html("<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Processing...");
                $('.btn-save').prop('disabled', true);
            }
        });
    }

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 43) {
            return false;
        }
        return true;
    }
</script>

<div>
	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(['id' => 'submit_form', 'action' => ['employees/store']]); ?>

    <?= Html::hiddenInput('Employees[id]', $model->id) ?>

    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?=
        $form->field($model, 'company_id')->widget(Select2::classname(), [
            'data' => $filterCompanies,
            'options' => ['placeholder' => 'Select a Company...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ])->label('Company');
    ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true])->input('email') ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true, "onkeypress" => "return isNumber(event)"]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-save']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employees/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

$this->title = $model->full_name;
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="bomanager-purchasing-order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'full_name',
            [
                'attribute' => 'company_id',
                'value' => $model->companies->name,
            ],
            [
                'attribute' => 'email',
                'format' => 'email',
                'value' => (is_null($model->email)) ? "" : $model->email,
            ],
            [
                'attribute' => 'phone',
                'format' => 'html',
                'value' => (is_null($model->phone)) ? "" : Html::a($model->phone, 'tel:'.$model->phone),
            ]
        ],
    ]) ?>

</div>