controllers/CompaniesController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use app\models\Companies;
use app\models\Employees;
use yii\web\UploadedFile;

class CompaniesController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['get'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $arrUserPermission = ['admin@admin.com'];
        if(!Yii::$app->user->isGuest && !in_array(Yii::$app->user->identity->email, $arrUserPermission)) {
            throw new \yii\web\HttpException(403, "You're not allowed for this action.");
        }

        return parent::beforeAction($action);
    }

    public function actionIndex() {
        $searchModel = new Companies();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate() {
        $model = new Companies();

        return $this->render('create', [
            'model' => $model
        ]);
    }

    public function actionStore() {
        $model = new Companies();

        if ($model->load(Yii::$app->request->post())) {
            $file_name = "";
            $current_logo = "";
            if(isset(Yii::$app->request->post('Companies')['id'])) {
                // update data companies
                $model = Companies::find()->where(['id' => Yii::$app->request->post('Companies')['id']])->one();
                $current_logo = $model->logo;

                $model->name = Yii::$app->request->post('Companies')['name'];
                $model->email = (Yii::$app->request->post('Companies')['email'] == "") ? NULL : Yii::$app->request->post('Companies')['email'];
                $model->website = Yii::$app->request->post('Companies')['website'];
            } else {
                $model->email = ($model->email == "") ? NULL : $model->email;
            }

            $logoFile = UploadedFile::getInstance($model, 'logo');
            if(!is_null($logoFile)) {
                $companyName = 'logo_'.str_replace(" ", "_", $model->name);
                $file_name = 'upload_image/' . $companyName . '.' . $logoFile->extension;
                $model->logo = "/".$file_name;
            } else {
                $model->logo = ($current_logo != "") ? $current_logo : "";
            }

            if($model->save()) {
                if(!is_null($logoFile)) {
                    $companyName = 'logo_'.str_replace(" ", "_", $model->name);
                    $file_name = 'upload_image/' . $companyName . '.' . $logoFile->extension;
                    $logoFile->saveAs($file_name);
                }

                Yii::$app->session->setFlash('success', 'Company created successfully');
                return $this->redirect('index');
            } else {
                Yii::$app->session->setFlash('error', 'There is something wrong, please try again');
                $model->logo = ($current_logo != "") ? $current_logo : "";
                $action = (!isset(Yii::$app->request->post('Companies')['id'])) ? 'create' : 'update';
                return $this->render($action, ['model' => $model]);
            }
        } else {
            Yii::$app->session->setFlash('error', 'There is something wrong, please try again');
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function actionView($id){
        $model = Companies::find()->where(['id' => $id])->one();

        if($model == null || empty($model)) {
            throw new NotFoundHttpException('Company does not exist.');
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = Companies::find()->where(['id' => $id])->one();

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $data = Companies::find()->where(['id' => $id])->one();
        $url_image = $data->logo;

        $delete = $data->delete();
        if($delete) {
            if (!is_null($url_image) && $url_image != "" && file_exists(Yii::$app->basePath . '/web/' . $url_image)) {
                unlink(Yii::$app->basePath . '/web/' . $url_image);
            }

            Yii::$app->session->setFlash('success', 'Company deleted successfully');
        } else {
            Yii::$app->session->setFlash('error', 'There is something wrong, please try again');
        }

        return $this->redirect(['index']);
    }

    public function actionCheckEmployee() {
        $data = Employees::find()
                ->where(['company_id' => $_POST['company_id']])
                ->count();

        $return = ['count' => $data];

        return $this->asJson($return);
    }
}

views/companies/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BomanagerMasterSupplier */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Create Company';
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<script type="text/javascript">
    window.onload = function() {
        $( "#submit_form" ).submit(function( event ) {
            if($('#companies-name').val() != "" && ($("#companies-logo")[0].files.length == 0 || $("#companies-logo")[0].files[0].size <= 1000000)) {
                $('.btn-save').html("<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Processing...");
                $('.btn-save').prop('disabled', true);
            }
        });
    }
</script>

<div>
	<h1><?= Html::encode($this->title) ?></h1>
	
    <?php $form = ActiveForm::begin(['id' => 'submit_form', 'action' => ['companies/store'], 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true])->input('email') ?>

    <?= $form->field($model, 'logo')->fileInput() ?>

    <?= $form->field($model, 'website')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-save']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/companies/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\bootstrap\ActiveForm;

$this->title = 'Companies';
$this->params['breadcrumbs'][] = $this->title;
?>
<script type="text/javascript">
    window.onload = function() {
        $( "#delete_form" ).submit(function( event ) {
            $('.btn-delete').html("<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Processing...");
            $('.btn-delete').prop('disabled', true);
            $('.btn-cancel-delete').prop('disabled', true);
        });
    }
    function showModalDelete(id, name) {
        var url_check_employee = <?php echo "'" . Url::to(['companies/check-employee']) . "'" ?>;

        $.ajax({
            url: url_check_employee,
            type: "POST",
            dataType: "json",
            data: {company_id: id},
            beforeSend: function() {
                $(".btn-modal-delete").html("<span class=\"glyphicon glyphicon-refresh glyphicon-refresh-animate\"></span>");
                $(".btn-modal-delete").prop("disabled", true);
            },
            success:function(response_data_json) {
                console.log(response_data_json.count);
                $(".btn-modal-delete").html("<span class=\"glyphicon glyphicon-trash\"></span>");
                $(".btn-modal-delete").prop("disabled", false);

                var msg = "";
                if(response_data_json.count > 0) {
                    msg = name+' cannot be deleted because there are still connected employee data';
                    $('.footer-delete').hide();
                } else {
                    msg = 'Company that are deleted cannot be returned. Are you sure you want to delete '+name+'?';
                    $('.footer-delete').show();
                }
                
                $("#modal").modal('show');
                $('#delete_form').attr('action', $('#delete_form').attr('action') + "?id="+id);
                $('.label-desc').html(msg);
            }
        });
    }
</script>

<div>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php 
            echo Html::a('Create Company', ['create'], ['class' => 'btn btn-success']);
        ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
            [
                'attribute' => 'email',
                'value' => function($model) {
                    return (is_null($model->email)) ? "" : $model->email;
                }
            ],
            [
                'attribute' => 'logo',
                'format' => 'html',
                'label' => 'Logo',
                'filter' => false,
                'contentOptions' => ['style' => 'text-align:center;'],
                'value' => function ($data) {
                    $baseurl = Url::base();
                    return Html::img($baseurl.$data['logo'] . '?v=' . date("His"), ["style" => "height:100px"]);
                },
            ],
            [
                'attribute' => 'website',
                'value' => function($model) {
                    return (is_null($model->website)) ? "" : $model->website;
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'buttons'=>[
                    'view'=>function ($url, $model) {
                        return  Html::a('<span class="glyphicon glyphicon-eye-open"></span>', 
                                        Url::to(['companies/view', 'id' => $model->id]), 
                                        ['class' => 'btn btn-primary btn-xs']
                                );
                    },
                    'update'=>function ($url, $model) {
                        return  Html::a('<span class="glyphicon glyphicon-pencil"></span>', 
                                        Url::to(['companies/update', 'id' => $model->id]), 
                                        ['class' => 'btn btn-warning btn-xs']
                                );
                    },
                    'delete'=>function ($url, $model) {
                        return  Html::button('<span class="glyphicon glyphicon-trash"></span>', 
                                            [
                                                'onclick'=> 'showModalDelete("'.$model->id.'", "'.$model->name.'");',
                                                'data-toggle'=>'tooltip',
                                                'title'=>Yii::t('app', 'Delete'),
                                                'class' => 'btn btn-danger btn-xs btn-modal-delete'
                                            ]
                                );
                    },
                ],
            ]
        ],
    ]); ?>


</div>

<?php
Modal::begin([
    'header' => '<h3 style="color:red;">WARNING!</h3>',
    'id' => 'modal',
    'size' => 'modal-md',
]);

ActiveForm::begin(['action' => ['companies/delete'], 'id' => 'delete_form', 'method' => 'post', 'layout' => 'horizontal', ]); ?>
<?= Html::csrfMetaTags() ?>
<div class='modal-body'>
    <p class="label-desc" style="font-weight: normal;"></p>
</div>
<div class="modal-footer footer-delete">
    <div class='form-group'>
        <button class='btn btn-danger btn-delete'><span class='glyphicon glyphicon-trash'></span> Yes</button>
        <button type="button" class="btn btn-success btn-cancel-delete" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span> No</button>
    </div>
</div>
<?php
ActiveForm::end();
Modal::end();
?>

views/companies/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\BomanagerMasterSupplier */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Update: '.$model->name;
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<script type="text/javascript">
    window.onload = function() {
        $( "#submit_form" ).submit(function( event ) {
            if($('#companies-name').val() != "") {
                $('.btn-save').html("<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Processing...");
                $('.btn-save').prop('disabled', true);
            }
        });
    }
</script>

<div>
	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(['id' => 'submit_form', 'action' => ['companies/store'], 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= Html::hiddenInput('Companies[id]', $model->id) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true])->input('email') ?>

    <div class="form-group">
    	<div>
    		<label class="control-label">Current Logo</label>
    	</div>
    	<div>
    		<?php if ($model->logo == "" || is_null($model->logo)): ?>
                <p class="text-danger">Logo has never been uploaded</p>
            <?php else : ?>
                <img src="<?php echo Url::base().$model->logo ?>" width=300 heigt=300>
            <?php endif ?>
    	</div>
    </div>

    <?= $form->field($model, 'logo')->fileInput(['value' => Url::base().$model->logo])->label('New Logo <smal>(only if you will change current logo)</small>') ?>

    <?= $form->field($model, 'website')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success btn-save']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/companies/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Companies', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="bomanager-purchasing-order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'email',
            [
                'attribute' => 'logo',
                'value' => Url::base().$model->logo . '?v=' . date("His"),
                'format' => ['image', ['width' => '300', 'height' => '300']],
            ],
            'website'
        ],
    ]) ?>

</div>